### ISSUE TITLE
Translate the project website to german

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/website#17]
Since most of our stakeholder are from germany it would be nice if the project website would also be available in german.

**Comment by Bachibouzouk** [comment]
@FredericHirschmueller - someone just needs to provide me with the translation of the contents, otherwise I let deepl do the job

**Comment by FredericHirschmueller** [comment]
I think it would be fine if you do it first with deepl and someone checks it afterwords.
