### ISSUE TITLE
[Website] the website should be updated and rearranged

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/website#18]
In many passages on the website the text describes that we are about to develope a planning tool. We should change the description and say that we already did that.

We should shift the link to the open-plan-tool to the top of the page.

**Comment by FredericHirschmueller** [comment]
The name of the tool for the registration is still written the old way. The new way is open-plan-tool.

![Unbenannt](https://user-images.githubusercontent.com/70587431/187862494-d03c2dcf-d32b-46f6-96c8-e1fe78655084.PNG)

**Comment by Bachibouzouk** [comment]
![Screenshot at 2023-01-12 16-16-48](https://user-images.githubusercontent.com/4399407/212105547-5676fa94-86b4-4414-8d01-ad2e291d486c.png)
I modified the order, what do you think the text should read?

We might need a different picture than the one with the crane, should we add a paragraph about the end of the project and how the open-plan-tool will be maintained in the future and about the potential paid/free trainings?

**Comment by FredericHirschmueller** [comment]
Would it be possible to change the form of the buttons for "Publications", GitHub", "ReadTheDocs" and "Youtube" from a rectangle to the form of an energy cell?

**Comment by FredericHirschmueller** [comment]
<img width="514" alt="Unbenannt" src="https://user-images.githubusercontent.com/70587431/212695519-e7dfcffd-c0a5-41b4-a736-76460acc0f8a.PNG">

**Comment by FredericHirschmueller** [comment]
That's just a sketch. the forms of the energy cells on the website are a little bit different. If we change the buttons like this, the shapes of the cells should look similar.

**Comment by Bachibouzouk** [comment]
> That's just a sketch. the forms of the energy cells on the website are a little bit different. If we change the buttons like this, the shapes of the cells should look similar. 

Good, if they are just surrounded by an hexagon but aligned it should not be too hard to implement :)

**Comment by c-moeller** [comment]
What do you think about taking the picture of the start page of the tool (which I adapted a bit for the poster) instead of the crane?

**Comment by c-moeller** [comment]
And I have another slightly off-topic point: Does it make sense to have some or the main participants from the stakeholder workshop as supporters on our website?

**Comment by FredericHirschmueller** [comment]
> And I have another slightly off-topic point: Does it make sense to have some or the main participants from the stakeholder workshops as supporters on our website?

I like the idea, but we would need to ask the stakeholder before we post their logos on our website. I could take care about that.

**Comment by Bachibouzouk** [comment]
> <img alt="Unbenannt" width="514" src="https://user-images.githubusercontent.com/70587431/212695519-e7dfcffd-c0a5-41b4-a736-76460acc0f8a.PNG">
> 
> That's just a sketch. the forms of the energy cells on the website are a little bit different. If we change the buttons like this, the shapes of the cells should look similar.

@bmlancien - do you know how to make this quickly? It would take me too much time to figure out

**Comment by Bachibouzouk** [comment]
I close this issue as I created two issues #21 and #22 for points that came along the discussion
